service: price-tracking-telegram-bot

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2

functions:
    send_price:
      handler: main.main
      events:
        - schedule: cron(0 8 * * ? *)
custom:
  pythonRequirements:
    dockerizePip: false
    usePipenv: true